version: "3.8"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_pmo_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
